const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
};

const ABOUT = {
  ABOUT_ME_P1: 'ABOUT_ME_P1',
  ABOUT_ME_P2: 'ABOUT_ME_P2',
  ABOUT_ME_P3: 'ABOUT_ME_P3',
  SKILLS: 'ABOUT_SKILLS',
  MORE_SKILLS: 'ABOUT_MORE_SKILLS',
};

export { ERRORS, ABOUT }