const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
};

const ABOUT = {
  ABOUT: 'ABOUT',
  ABOUT_TITLE: 'ABOUT_TITLE',
  ABOUT_TITLE_HIDE_DIV: 'ABOUT_TITLE_HIDE_DIV',
  ABOUT_ME_P1: 'ABOUT_ME_P1',
  ABOUT_ME_P2: 'ABOUT_ME_P2',
  ABOUT_ME_P3: 'ABOUT_ME_P3',
  SKILLS: 'ABOUT_SKILLS',
  MORE_SKILLS: 'ABOUT_MORE_SKILLS',
};

const PROJECT = {
  PROJECT: 'PROJECT',
  PROJECT_TITLE_LEFT: 'PROJECT_TITLE_LEFT',
  PROJECT_TITLE_RIGHT: 'PROJECT_TITLE_RIGHT',
  PROJECT_TITLE_BINARY: 'PROJECT_TITLE_BINARY',
}

export { ERRORS, ABOUT, PROJECT }