const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
};

const ABOUT = {
  ABOUT: 'ABOUT',
  ABOUT_TITLE: 'ABOUT_TITLE',
  ABOUT_TITLE_HIDE_DIV: 'ABOUT_TITLE_HIDE_DIV',
  ABOUT_ME_P1: 'ABOUT_ME_P1',
  ABOUT_ME_P2: 'ABOUT_ME_P2',
  ABOUT_ME_P3: 'ABOUT_ME_P3',
  SKILLS: 'ABOUT_SKILLS',
  MORE_SKILLS: 'ABOUT_MORE_SKILLS',
};

const PROJECT = {
  PROJECT: 'PROJECT',
  PROJECT_TITLE: 'PROJECT_TITLE',
  PROJECT_BINARY: 'PROJECT_BINARY',
}

const EMAIL = {
  EMAIL_SEND: 'EMAIL_SEND'
}

export { ERRORS, ABOUT, PROJECT, EMAIL }